baseurl = "https://viniciusvdias.github.io"
title = "Vinicius Dias"
copyright = "&copy; 2016 Vinicius Dias"
languageCode = "en-us"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-88914386-1"

[params]
  name = "Vinicius Dias"
  role = ""
  organization = "Computer Science Department, UFMG, Brazil"
  avatar = "profile3-squared.jpg"
  email = "viniciusvdias@dcc.ufmg.br"
  address = "Speed Lab, Universidade Federal de Minas Gerais, Belo Horizonte, BRA."
  phone = ""

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Enable native social sharing buttons?
  sharing = false

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = ["red.css"]
  custom_js  = []


  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:viniciusvdias@dcc.ufmg.br"

  #[[params.social]]
  #  icon = "twitter"
  #  icon_pack = "fa"
  #  link = "https://twitter.com/viniciusvdias"

  #[[params.social]]
  #  icon = "google-scholar"
  #  icon_pack = "ai"
  #  link = "https://scholar.google.co.uk/citations?user=sIwtMXoAAAAJ"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/viniciusvdias"
  
  [[params.social]]
    icon = "facebook"
    icon_pack = "fa"
    link = "//facebook.com/vvsdias"
  
  [[params.social]]
    link = "//facebook.com/vvsdias"


# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications"
  weight = 2

#[[menu.main]]
#  name = "Posts"
#  url = "#posts"
#  weight = 3
#
#[[menu.main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 4

[[menu.main]]
  name = "Talks"
  url = "#talks"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6
